---
- hosts: casserver
  remote_user: root

  vars:
    jdk_rpm_file: jdk-8u151-linux-x64.rpm
    package_directory: /root
    temp_folder: /tmp
    fqdn: casserver.shq.local

  tasks:
          
    - name: Transferer le fichier RPM sur le serveur
      copy:
        src: "{{ package_directory }}/{{ jdk_rpm_file }}"
        dest: "{{ temp_folder }}"
  
    - name: Installer le package Oracle JDK 
      yum:
       name: "{{ temp_folder }}/{{ jdk_rpm_file }}"
       state: present
       
    - name: Generate RSA Key
      command: openssl genrsa \
        -out "/tmp/key.pem" 2048
      args:
        creates: "/tmp/key.pem"

    - name: Generate CSR
      command: openssl req \
        -new \
        -subj '/C=US/ST=CA/L=Mountain View/O=Jasmeet/CN={{ fqdn }}'
        -key "/tmp/key.pem" \
        -out "/tmp/csr.pem"
      args:
        creates: "/tmp/csr.pem"

    - name: Generate Self-signed Certificate
      command: openssl req \
        -x509 \
        -days 1825 \
        -key "/tmp/key.pem" \
        -in "/tmp//csr.pem" \
        -out "/tmp/cert.pem"
      args:
        creates: "/tmp/cert.pem"
