---
- hosts: cas-server
  remote_user: root

  vars:
    jdk_rpm_file: jdk-8u151-linux-x64.rpm
    package_directory: /root
    temp_folder: /tmp
    fqdn: cas-server.shqrip.lab
    server: cas-server

  tasks:
          
    - name: Transferer le fichier RPM sur le serveur
      copy:
        src: "{{ package_directory }}/{{ jdk_rpm_file }}"
        dest: "{{ temp_folder }}"
  
    - name: Installer le package Oracle JDK 
      yum:
       name: "{{ temp_folder }}/{{ jdk_rpm_file }}"
       state: present
       
    - name: Creer le certificat auto-signé
      command: /opt/jdk1.8.0_151/bin/keytool -genkey -alias cas -keyalg RSA -validity 999 \
        -keystore /etc/cas/thekeystore \
        -ext san=dns:cas-server.shqrip.lab
      args:
        creates: "/tmp/{{ server }}.key"

    - name: Generate CSR
      command: openssl req \
        -new \
        -subj '/C=CA/ST=QC/L=Societe/O=SHQ/CN={{ fqdn }}'
        -key "/tmp/{{ server }}.key" \
        -out "/tmp/{{ server }}.csr"
      args:
        creates: "/tmp/{{ server }}.csr"

    - name: Generate Self-signed Certificate
      command: openssl req \
        -x509 \
        -days 1825 \
        -key "/tmp/{{ server }}.key" \
        -in "/tmp/{{ server }}.csr" \
        -out "/tmp/{{ server }}.crt"
      args:
        creates: "/tmp/{{ server }}.crt"
        
    - name: Import SSL certificate from services.gradle.org to a given cacerts keystore
      java_cert:
        cert_path: /tmp/{{ server }}.crt
        cert_alias: cas-server
        executable: /usr/java/jdk1.8.0_151/bin/keytool
        keystore_path: /etc/cas/cas-server
        keystore_pass: changeit
        keystore_create: yes
        state: present
        
