---
- hosts: cas_build
  remote_user: root

  vars:
    jdk_rpm_file: jdk-8u151-linux-x64.rpm
    package_directory: /root
    temp_folder: /tmp

  tasks:
  
    - name: Transferer le fichier RPM sur le serveur
      copy:
        src: "{{ package_directory }}/{{ jdk_rpm_file }}"
        dest: "{{ temp_folder }}"
  
    - name: Installer le package Oracle JDK 
      yum:
       name: "{{ temp_folder }}/{{ jdk_rpm_file }}"
       state: present
       
    - name: Installer le package GIT
      yum:
       name: git
       state: latest
       
    - name: Deactiver la vérification des certificats pour GIT
      lineinfile:
       path: /etc/environment
       regexp: '^GIT_SSL_NO_VERIFY='
       line: 'GIT_SSL_NO_VERIFY=true'   
       
    - name: Rediriger requete HTTP via Proxy
      lineinfile:
       path: /etc/environment
       regexp: '^http_proxy='
       line: 'http_proxy="http://qxdpxe01.dev.shq.local:8080/"'   

    - name: Rediriger requete HTTP via Proxy
      lineinfile:
       path: /etc/environment
       regexp: '^https_proxy='
       line: 'https_proxy="http://qxdpxe01.dev.shq.local:8080/"'   

#
# Si Overlay avec Gradle
#
              
    - name: Importer le certificat SSL "services.gradle.org" dans le keystore
      java_cert:
        cert_url: services.gradle.org
        cert_port: 443
        keystore_path: /usr/java/jdk1.8.0_151/jre/lib/security/cacerts
        keystore_pass: changeit
        state: absent
        
    - name: Importer le certificat SSL "jcenter.bintray.com" dans le keystore
      java_cert:
        cert_url: jcenter.bintray.com
        cert_port: 443
        keystore_path: /usr/java/jdk1.8.0_151/jre/lib/security/cacerts
        keystore_pass: changeit
        state: absent

    - name: Importer le certificat SSL "dl.bintray.com" dans le keystore
      java_cert:
        cert_url: dl.bintray.com
        cert_port: 443
        keystore_path: /usr/java/jdk1.8.0_151/jre/lib/security/cacerts
        keystore_pass: changeit
        state: absent

    - name: Importer le certificat SSL "raw.githubusercontent.com" dans le keystore
      java_cert:
        cert_url: raw.githubusercontent.com
        cert_port: 443
        keystore_path: /usr/java/jdk1.8.0_151/jre/lib/security/cacerts
        keystore_pass: changeit
        state: absent

    - name: Importer le certificat SSL "oss.sonatype.org" dans le keystore
      java_cert:
        cert_url: oss.sonatype.org
        cert_port: 443
        keystore_path: /usr/java/jdk1.8.0_151/jre/lib/security/cacerts
        keystore_pass: changeit
        state: absent

    - name: Importer le certificat SSL "build.shibboleth.net" dans le keystore
      java_cert:
        cert_url: build.shibboleth.net
        cert_port: 443
        keystore_path: /usr/java/jdk1.8.0_151/jre/lib/security/cacerts
        keystore_pass: changeit
        state: absent




#    - name: Import SSL certificate from services.gradle.org to a given cacerts keystore
#      java_cert:
#        cert_url: services.gradle.org
#        cert_port: 443
#        keystore_path: /usr/java/jdk1.8.0_151/jre/lib/security/cacerts
#        keystore_pass: changeit
#        state: present
