---
- hosts: cas_build
  remote_user: root

  vars:
    jdk_rpm_file: jdk-8u151-linux-x64.rpm
    package_directory: /root
    temp_folder: /tmp

  tasks:
  
    - name: Transferer le fichier RPM sur le serveur
      copy:
        src: "{{ package_directory }}/{{ jdk_rpm_file }}"
        dest: "{{ temp_folder }}"
  
    - name: Installer le package Oracle JDK 
      yum:
       name: "{{ temp_folder }}/{{ jdk_rpm_file }}"
       state: present
       
    - name: Installer le package GIT
      yum:
       name: git
       state: latest
       
    - name: Déactiver la vérification des certificats pour GIT
      lineinfile:
       path: /etc/environment
       regexp: '^GIT_SSL_NO_VERIFY='
       line: 'GIT_SSL_NO_VERIFY=true'   
       
       
#    - name: Import SSL certificate from repository.apache.org to a given cacerts keystore
#      java_cert:
#        cert_url: repository.apache.org
#        cert_port: 443
#        keystore_path: /usr/java/jdk1.8.0_151/jre/lib/security/cacerts
#        keystore_pass: changeit
#        state: present

#    - name: Import SSL certificate from services.gradle.org to a given cacerts keystore
#      java_cert:
#        cert_url: services.gradle.org
#        cert_port: 443
#        keystore_path: /usr/java/jdk1.8.0_151/jre/lib/security/cacerts
#        keystore_pass: changeit
#        state: present
