---
- hosts: localhost
  remote_user: root
  sudo: yes
  vars:
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u151-b12/jdk-8u151-linux-x64.rpm
    download_folder: /tmp
    java_name: "{{download_folder}}/jdk1.8.0_05"
    java_rpm: "{{download_folder}}/jdk-8u151-linux-x64.rpm"


  tasks:
  
    - name: Install Oracle JDK 
      yum:
       name: /root/jdk-8u151-linux-x64.rpm
       state: present
       
    - name: Import SSL certificate from repository.apache.org to a given cacerts keystore
      java_cert:
        cert_url: repository.apache.org
        cert_port: 443
        keystore_path: /usr/java/jdk1.8.0_151/jre/lib/security/cacerts
        keystore_pass: changeit
        state: present

    - name: Import SSL certificate from services.gradle.org to a given cacerts keystore
      java_cert:
        cert_url: services.gradle.org
        cert_port: 443
        keystore_path: /usr/java/jdk1.8.0_151/jre/lib/security/cacerts
        keystore_pass: changeit
        state: present
