---
- hosts: localhost
  remote_user: root
  sudo: yes
  vars:
    download_url: http://download.oracle.com/otn-pub/java/jdk/8u151-b12/jdk-8u151-linux-x64.rpm
    download_folder: /tmp
    java_name: "{{download_folder}}/jdk1.8.0_05"
    java_archive: "{{download_folder}}/jdk-8u5-linux-x64.tar.gz"


  tasks:
  
  - name: Télécharger le JDK
    get_url:
      url: "{{download_url}}"
      dest: "{{download_folder}}"
 
