---
- hosts: test
  remote_user: root

  vars:
    jdk_rpm_file: jdk-8u151-linux-x64.rpm
    package_directory: /root
    temp_folder: /tmp
    fqdn: cas-server.shqrip.lab
    java_home: /usr/java/jdk1.8.0_151

  tasks:
          
    - name: Transferer le fichier RPM sur le serveur
      copy:
        src: "{{ package_directory }}/{{ jdk_rpm_file }}"
        dest: "{{ temp_folder }}"
  
    - name: Installer le package Oracle JDK 
      yum:
       name: "{{ temp_folder }}/{{ jdk_rpm_file }}"
       state: present
       
    - name: Rediriger requete HTTP via Proxy       
      shell: "export $JAVA_HOME={{ java_home }}"
       
#    - name: Rediriger requete HTTP via Proxy
#      lineinfile:
#       path: /etc/environment
#       regexp: '^JAVA_HOME='
#       line: 'JAVA_HOME="{{ java_home }}"' 
